### ISSUE TITLE
wp package install wp-checksum Error: Invalid package.

### ISSUE THREAD

**Issue by josenobile** [eriktorsner/wp-checksum#6]
Hello, 

wp package install wp-checksum
Error: Invalid package.

**Comment by eriktorsner** [comment]
Hi Jose, thanks for the bug report.

I'm thinking this could be a php version issue, but I'm not sure. Could you tell me the full output of the following two commands: `wp --info` and `wp package install wpchecksum`. I'll set up a vagrant with a similar environment and see if I can recreate the bug.

Here's what I have:

```
vagrant@devenv:/vagrant$ wp --info
PHP binary:	/usr/bin/php7.0
PHP version:	7.0.8-0ubuntu0.16.04.3
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/home/vagrant/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	/vagrant/wp-cli.yml
WP-CLI version:	1.0.0

vagrant@devenv:/vagrant$ wp package install wp-checksum
Installing package eriktorsner/wp-checksum (dev-master)
Updating /home/vagrant/.wp-cli/packages/composer.json to require the package...
Registering /vagrant/wp-checksum as a path repository...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.790 seconds
Analyzed 3453 packages to resolve dependencies
Analyzed 87730 rules to resolve dependencies
 - Installing pimple/pimple (dev-master ac03ac9)
 - Installing eriktorsner/wp-checksum (dev-master 6ed1a5e)
Writing lock file
Generating autoload files
---
Success: Package installed.

```

**Comment by josenobile** [comment]
Hello Erik,

wp --info
PHP binary:     /opt/alt/php56/usr/bin/php
PHP version:    5.6.30
php.ini used:   /opt/alt/php56/etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:    /home/ipssoits/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.0.0

wp package install wpchecksum
Error: Invalid package.

Just a bit of information, it is Cloudlinux with cagefs, wp is installed global and put available inside the cagefs. wp  works fine with the standard subcommands (download, plugin, theme, verify-checksums , etc)

**Comment by phillcoxon** [comment]
I'm having the same issue here too - "invalid package". 

 [~/www/wp-content/plugins]# wp --info
PHP binary:	/usr/local/bin/php
PHP version:	5.6.28
php.ini used:	/usr/local/lib/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/home/ioss/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	1.0.0

[~/www/wp-content/plugins]# wp package install wp-checksum
Error: Invalid package.

 [~/www/wp-content/plugins]# wp package install wpchecksum
Error: Invalid package.

Tested on 2 x centos servers, one running cloudlinux, the other not. 

Thanks in advance!

**Comment by eriktorsner** [comment]
Hi Phil and thanks for reporting,

I've successfully recreated this issue on a blank Ubuntu 16.04 server. For me, the issue is solved by passing the fully qualified package name (eriktorsner/wp-checksum) as the package name rather than just the "slug" (wp-checksum),

Works:
```
$ wp package install eriktorsner/wp-bootstrap
Installing package eriktorsner/wp-bootstrap (dev-master)
Updating /home/vagrant/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
...

```
Doesn't work:
```
$ wp package install wp-checksum
Error: Invalid package.

```

This is consistent with other 3rd party packages, so it's a documentation bug. I've updated the README file accordingly.

On a side note. I'm a little bit surprised since in my own testing as well as when I originally answered @josenobile 3 weeks ago, using just "wp-checksum" as the argument did in fact work. However, on a fresh install it's obvious that it doesn't.

For reference, I tried this in a fresh vagrant machine with the bare minimum php packages installed, just the ones that are installed as dependencies of the php base package.

**OS**: Ubuntu 16.04
**PHP**: 7.0
**Packages**: php-common php7.0 php7.0-cli php7.0-common php7.0-fpm php7.0-json php7.0-opcache php7.0-readline
